SYMB_APP/models.py
from SYMB_APP import db



class Contact(db.Model):
    __tablename__='Contacts'
    email = db.Column(db.Text,  nullable=False)
    name = db.Column(db.Text, nullable=False)
    phone_number = db.Column(db.Numeric, nullable=False)
    id = db.Column(db.Integer, primary_key=True)

    def __repr__(self):
        return f"Contact('{self.name}', '{self.email}','{self.phone_number}')"

SYMB_APP/contacts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email, Length


class ContactForm(FlaskForm):
    name = StringField('name', validators=[DataRequired(),Length(min=2,max=50)])
    phone_number = StringField('phone_number', validators=[DataRequired(),Length(10)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Save Contact')

SYMB_APP/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from SYMB_APP.config import Config
from flask_migrate import Migrate
db=SQLAlchemy()
migrate=Migrate()
def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)
    db.init_app(app)
    migrate.init_app(app, db)
    with app.app_context():
        from SYMB_APP.main.routes import main
        from SYMB_APP.contacts.routes import contacts
        app.register_blueprint(contacts)
        app.register_blueprint(main)
        db.create_all()
    

    return app
        

SYMB_APP/contacts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from SYMB_APP import db
from SYMB_APP.models import Contact
from SYMB_APP.contacts.forms import ContactForm

contacts = Blueprint('contacts', __name__)


@contacts.route("/contact/new", methods=['GET', 'POST'])
def new_contact():
    form = ContactForm()
    if form.validate_on_submit():
        contact = Contact(name=form.name.data, phone_number=form.phone_number.data, email=form.email.data)
        db.session.add(contact)
        db.session.commit()
        flash('Your contact has been added!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_contact.html', title='New Contact',
                           form=form, legend='New Contact')


@contacts.route("/contact/<int:contact_id>/update", methods=['GET', 'POST'])
def update_contact(contact_id):
    contact = Contact.query.get_or_404(contact_id)
    form = ContactForm()
    if form.validate_on_submit():
        contact.name = form.name.data
        contact.phone_number = form.phone_number.data
        contact.email = form.email.data
        db.session.commit()
        flash('Your contact has been updated!', 'success')
        return redirect(url_for('main.home'))
    elif request.method == 'GET':
        form.name.data = contact.name
        form.email.data = contact.email
        form.phone_number.data = contact.phone_number
    return render_template('create_contact.html', title='Update Contact',
                           form=form, legend='Update Contact')


@contacts.route("/contact/<int:contact_id>/delete", methods=['GET', 'POST'])

def delete_contact(contact_id):
    contact = Contact.query.get_or_404(contact_id)
    db.session.delete(contact)
    db.session.commit()
    flash('Your contact has been deleted!', 'success')
    return redirect(url_for('main.home'))

SYMB_APP/main/routes.py
from flask import render_template, request, Blueprint
from SYMB_APP.models import Contact
main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    contacts = Contact.query.order_by(Contact.id.asc()).paginate(page=page, per_page=5)
    
    return render_template('home.html', contacts=contacts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

SYMB_APP/routes.py
from flask import render_template, request
from SYMB_APP.models import Contact
from SYMB_APP import app


@app.route("/")
@app.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    contacts = Contact.query.order_by(Contact.id.asc()).paginate(page=page, per_page=5)
    
    return render_template('home.html', contacts=contacts)


@app.route("/about")
def about():
    return render_template('about.html', title='About')

SYMB_APP/templates/create_contact.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.phone_number.label(class="form-control-label") }}
                {% if form.phone_number.errors %}
                    {{ form.phone_number(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.phone_number(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

SYMB_APP/templates/home.html
{% extends "layout.html"%}
{% block content %}
  
  
<a  href="{{ url_for('contacts.new_contact') }}">
  <button type="button" class="btn btn-primary float-end btn-sm" data-toggle="modal" data-target="#mymodal">
    Add New Contact</button></a>
  <table class="table table-hover table-info">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Phone Number</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
    {% for contact in contacts%}
    <tr>
      <td>{{contact.id}}</td>
      <td>{{contact.name}}</td>
      <td>{{contact.phone_number}}</td>
      <td>{{contact.email}}</td>
      <td>
    <a href="{{ url_for('contacts.update_contact',contact_id=contact.id)}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#editmodal">Edit</a>
    <a href="{{ url_for('contacts.delete_contact',contact_id=contact.id )}}" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#deletemodal">Delete</a>
      </td>
    </tr>
    {% endfor %}


  

  
  {% endblock content %}

SYMB_APP/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask CRUD</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>

    <main role="main" class="container bg-light">
      <div class="row ">
        <div class="column">
          <h1  class="text-center text-success">FLASK CRUD APP CONTACT DETAILS</h1>
  
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}

            {% block content %}{% endblock %}
                </div>
              </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>